//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiJdr.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class classe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public classe()
        {
            this.personnage = new HashSet<personnage>();
        }

        public int ID_CLASSE { get; set; }
        public short MAX_VIE { get; set; }
        public short MAX_MANA { get; set; }
        public short PUISSANCE { get; set; }
        public short MAGIE { get; set; }
        public short DEXTERITE { get; set; }
        public short OBSERVATION { get; set; }
        public short INTELLIGENCE { get; set; }
        public short CHANCE { get; set; }
        public short CHARISME { get; set; }
        public string DESIGNATION { get; set; }
        public string DESCRIPTION { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnage> personnage { get; set; }
    }
}
