//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiJdr.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jdrEntities : DbContext
    {
        public jdrEntities()
            : base("name=jdrEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<classe> classe { get; set; }
        public virtual DbSet<image> image { get; set; }
        public virtual DbSet<joueur> joueur { get; set; }
        public virtual DbSet<log> log { get; set; }
        public virtual DbSet<objet> objet { get; set; }
        public virtual DbSet<partie> partie { get; set; }
        public virtual DbSet<personnage> personnage { get; set; }
        public virtual DbSet<stock> stock { get; set; }
        public virtual DbSet<utilisateur> utilisateur { get; set; }
    }
}
