//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiJdr.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class joueur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public joueur()
        {
            this.personnage = new HashSet<personnage>();
        }
    
        public int ID_JOUEUR { get; set; }
        public int ID_UTIL { get; set; }
        public string ID_PARTIE { get; set; }
        public bool IS_MJ { get; set; }
    
        public virtual utilisateur utilisateur { get; set; }
        [JsonIgnore]
        public virtual partie partie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnage> personnage { get; set; }
    }
}
