//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiJdr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int ID_INVENTAIRE { get; set; }
        public int ID_PERSO { get; set; }
        public int ID_OBJET { get; set; }
        public short QUANTITE { get; set; }
    
        public virtual objet objet { get; set; }
        public virtual personnage personnage { get; set; }
    }
}
