//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiJdr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_log
    {
        public int id_log { get; set; }
        public string id_partie { get; set; }
        public Nullable<int> id_perso { get; set; }
        public sbyte type { get; set; }
        public System.DateTime date { get; set; }
        public byte[] image { get; set; }
        public string text { get; set; }
    
        public virtual t_partie t_partie { get; set; }
        public virtual t_personnage t_personnage { get; set; }
    }
}
