//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiJdr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_personnage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_personnage()
        {
            this.t_log = new HashSet<t_log>();
        }
    
        public int id_perso { get; set; }
        public string id_partie { get; set; }
        public int id_util { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public Nullable<bool> MJ { get; set; }
        public Nullable<bool> Actif { get; set; }
        public int PV { get; set; }
        public int PM { get; set; }
        public int XP { get; set; }
        public int LVL { get; set; }
        public int PF { get; set; }
        public int magie { get; set; }
        public int dext { get; set; }
        public int observ { get; set; }
        public int intel { get; set; }
        public int chance { get; set; }
        public int charisme { get; set; }
        public string bloc { get; set; }
        public string classe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_log> t_log { get; set; }
        public virtual t_partie t_partie { get; set; }
        public virtual t_utilisateur t_utilisateur { get; set; }
    }
}
